apiVersion: v1
kind: ConfigMap
metadata:
  name: hocbong-config
  namespace: hocbong-vn
data:
  NODE_ENV: "production"
  PORT: "3000"
  NEXT_TELEMETRY_DISABLED: "1"
  BOT_USER_AGENT: "HocBongVN-Bot/2.2 (+https://hocbong.vn/bot)"
  CRAWL_INTERVAL_CRON: "*/20 * * * *"
