apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: hocbong-ingress
  namespace: hocbong-vn
  annotations:
    kubernetes.io/ingress.class: "nginx"
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    nginx.ingress.kubernetes.io/proxy-body-size: "10m"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
spec:
  tls:
    - hosts:
        - hocbong.vn
        - www.hocbong.vn
      secretName: hocbong-tls-secret
  rules:
    - host: hocbong.vn
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: hocbong-service
                port:
                  number: 80
    - host: www.hocbong.vn
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: hocbong-service
                port:
                  number: 80
