apiVersion: v1
kind: Secret
metadata:
  name: hocbong-secrets
  namespace: hocbong-vn
type: Opaque
stringData:
  DATABASE_URL: "file:/app/prisma/prod.db" # or "postgresql://user:pass@postgres:5432/hocbong"
  JWT_SECRET: "replace-with-ultra-secure-min-64-character-production-jwt-secret-key-hocbong"
  ENCRYPTION_KEY: "0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef"
  RESEND_API_KEY: ""
  BREVO_API_KEY: ""
