// ════════════════════════════════════════════════════════════
// Danh Mục Nguồn Dữ Liệu Tuyển Sinh, Học Bổng & Việc Làm (150+ Nguồn)
// Tích hợp từ 126 cổng chính thức qua 21 Quốc gia & Bộ GD&ĐT
// ════════════════════════════════════════════════════════════

export type FetchStrategy = 'HTML' | 'API' | 'RSS';
export type SourceTier = 'A' | 'B' | 'C';
export type SourceKind = 'UNIVERSITY' | 'GOVERNMENT' | 'NGO' | 'CORPORATE' | 'PORTAL';

export interface SourceConfig {
  name: string;
  baseUrl: string;
  kind: SourceKind;
  tier: SourceTier;
  fetchStrategy: FetchStrategy;
  country?: string;
  category?: string;
  features?: string;
  language?: string;
  appFee?: string;
  deadlinePattern?: string;
  notes?: string;
}

export const INITIAL_SOURCES: SourceConfig[] = [
  {
    "name": "Cổng thông tin tuyển sinh Bộ GD&ĐT",
    "baseUrl": "https://tuyensinh.moet.gov.vn",
    "kind": "GOVERNMENT",
    "tier": "A",
    "fetchStrategy": "HTML",
    "country": "Vietnam",
    "category": "Undergraduate Admissions",
    "features": "Tra cứu trường/ngành/phương thức; hướng dẫn đăng ký nguyện vọng; công bố quy chế/thông tư; thanh toán lệ phí online; hotline/email hỗ trợ",
    "language": "Vietnamese",
    "appFee": "Free",
    "deadlinePattern": "Year-round (official deadlines per year)",
    "notes": "Official government portal; legal authority"
  },
  {
    "name": "Hệ thống đăng ký xét tuyển chung",
    "baseUrl": "http://thisinh.thitotnghiepthpt.edu.vn",
    "kind": "UNIVERSITY",
    "tier": "B",
    "fetchStrategy": "HTML",
    "country": "Vietnam",
    "category": "Undergraduate Admissions",
    "features": "Đăng ký 15 nguyện vọng; nộp lệ phí; xác nhận nhập học; tra cứu kết quả; điều chỉnh sai sót điểm THPT; tài khoản CCCD",
    "language": "Vietnamese",
    "appFee": "Free",
    "deadlinePattern": "2/7 - 14/7 (registration); 15/7 - 21/7 (fee payment)",
    "notes": "Centralized system for all public universities"
  },
  {
    "name": "Cổng dịch vụ công Quốc gia",
    "baseUrl": "https://dichvucong.gov.vn",
    "kind": "GOVERNMENT",
    "tier": "A",
    "fetchStrategy": "HTML",
    "country": "Vietnam",
    "category": "Undergraduate Admissions",
    "features": "Đăng ký xét tuyển qua VNeID; tra cứu thủ tục hành chính",
    "language": "Vietnamese",
    "appFee": "Free",
    "deadlinePattern": "Same as above",
    "notes": "Alternative access via national digital ID"
  },
  {
    "name": "Tuyensinh247",
    "baseUrl": "https://tuyensinh247.com",
    "kind": "UNIVERSITY",
    "tier": "B",
    "fetchStrategy": "HTML",
    "country": "Vietnam",
    "category": "Undergraduate Admissions",
    "features": "Tổng hợp 264+ trường; tính điểm học bạ; tra cứu điểm chuẩn/chỉ tiêu/tổ hợp môn; cập nhật realtime",
    "language": "Vietnamese",
    "appFee": "Free",
    "deadlinePattern": "Continuous updates",
    "notes": "Popular private portal; real-time data"
  },
  {
    "name": "Lao Động - Tuyển sinh",
    "baseUrl": "https://laodong.vn/tuyen-sinh",
    "kind": "UNIVERSITY",
    "tier": "B",
    "fetchStrategy": "HTML",
    "country": "Vietnam",
    "category": "Undergraduate Admissions",
    "features": "Danh sách trường công bố phương án/điểm sàn/điểm chuẩn; tin tức chính sách; hướng nghiệp",
    "language": "Vietnamese",
    "appFee": "Free",
    "deadlinePattern": "News-based",
    "notes": "Official newspaper; reliable policy updates"
  },
  {
    "name": "Vietnam.vn - Giáo dục",
    "baseUrl": "https://www.vietnam.vn/giao-duc",
    "kind": "UNIVERSITY",
    "tier": "B",
    "fetchStrategy": "HTML",
    "country": "Vietnam",
    "category": "Undergraduate Admissions",
    "features": "Tra cứu điểm chuẩn cả nước; danh sách trường xét học bạ; hướng dẫn đăng ký",
    "language": "Vietnamese",
    "appFee": "Free",
    "deadlinePattern": "Government schedule",
    "notes": "Government e-portal"
  },
  {
    "name": "HOCMAI - Hướng nghiệp",
    "baseUrl": "https://huongnghiep.hocmai.vn",
    "kind": "UNIVERSITY",
    "tier": "B",
    "fetchStrategy": "HTML",
    "country": "Vietnam",
    "category": "Undergraduate Admissions",
    "features": "Danh sách trường mở cổng đăng ký; tư vấn ngành nghề; ôn thi online",
    "language": "Vietnamese",
    "appFee": "Free",
    "deadlinePattern": "Continuous",
    "notes": "Private education platform"
  },
  {
    "name": "VietJack - Tuyển sinh",
    "baseUrl": "https://khoahoc.vietjack.com/tuyen-sinh",
    "kind": "UNIVERSITY",
    "tier": "B",
    "fetchStrategy": "HTML",
    "country": "Vietnam",
    "category": "Undergraduate Admissions",
    "features": "Tra cứu mã trường, mã ngành, tổ hợp xét tuyển, điểm chuẩn các năm",
    "language": "Vietnamese",
    "appFee": "Free",
    "deadlinePattern": "Static data",
    "notes": "Reference database"
  },
  {
    "name": "TopCV - Cẩm nang tuyển sinh",
    "baseUrl": "https://www.topcv.vn/cam-nang/tuyen-sinh",
    "kind": "CORPORATE",
    "tier": "B",
    "fetchStrategy": "HTML",
    "country": "Vietnam",
    "category": "Undergraduate Admissions",
    "features": "Hướng dẫn đăng ký; so sánh phương thức; mẹo chọn nguyện vọng",
    "language": "Vietnamese",
    "appFee": "Free",
    "deadlinePattern": "Seasonal",
    "notes": "Career platform content"
  },
  {
    "name": "Trang tuyển sinh ĐHQGHN",
    "baseUrl": "https://tuyensinh.vnu.edu.vn",
    "kind": "UNIVERSITY",
    "tier": "B",
    "fetchStrategy": "HTML",
    "country": "Vietnam",
    "category": "Undergraduate Admissions",
    "features": "Thông tin 9 trường thành viên; đăng ký xét tuyển riêng",
    "language": "Vietnamese",
    "appFee": "Free",
    "deadlinePattern": "Per university",
    "notes": "VNU member universities"
  },
  {
    "name": "Trang tuyển sinh ĐHQG HCM",
    "baseUrl": "https://tuyensinh.vnuhcm.edu.vn",
    "kind": "UNIVERSITY",
    "tier": "B",
    "fetchStrategy": "HTML",
    "country": "Vietnam",
    "category": "Undergraduate Admissions",
    "features": "Thông tin 9 trường thành viên ĐHQG HCM",
    "language": "Vietnamese",
    "appFee": "Free",
    "deadlinePattern": "Per university",
    "notes": "VNU-HCM member universities"
  },
  {
    "name": "Tuyển sinh ĐH Bách Khoa Hà Nội",
    "baseUrl": "https://tuyensinh.uet.vnu.edu.vn",
    "kind": "UNIVERSITY",
    "tier": "B",
    "fetchStrategy": "HTML",
    "country": "Vietnam",
    "category": "Undergraduate Admissions",
    "features": "Đăng ký xét tuyển online; tra cứu điểm chuẩn; hướng nghiệp",
    "language": "Vietnamese",
    "appFee": "Free",
    "deadlinePattern": "Per university",
    "notes": "Top engineering university"
  },
  {
    "name": "Tuyển sinh ĐH Bách Khoa TP.HCM",
    "baseUrl": "https://tuyensinh.hcmut.edu.vn",
    "kind": "UNIVERSITY",
    "tier": "B",
    "fetchStrategy": "HTML",
    "country": "Vietnam",
    "category": "Undergraduate Admissions",
    "features": "Đăng ký xét tuyển; tra cứu điểm chuẩn; chương trình đào tạo",
    "language": "Vietnamese",
    "appFee": "Free",
    "deadlinePattern": "Per university",
    "notes": "Top engineering university South"
  },
  {
    "name": "Tuyển sinh ĐH Kinh tế Quốc dân",
    "baseUrl": "https://tuyensinh.neu.edu.vn",
    "kind": "UNIVERSITY",
    "tier": "B",
    "fetchStrategy": "HTML",
    "country": "Vietnam",
    "category": "Undergraduate Admissions",
    "features": "Thông tin tuyển sinh; học bổng doanh nghiệp; hướng nghiệp",
    "language": "Vietnamese",
    "appFee": "Free",
    "deadlinePattern": "Per university",
    "notes": "Business focus"
  },
  {
    "name": "Tuyển sinh ĐH Ngoại Thương",
    "baseUrl": "https://tuyensinh.ftu.edu.vn",
    "kind": "UNIVERSITY",
    "tier": "B",
    "fetchStrategy": "HTML",
    "country": "Vietnam",
    "category": "Undergraduate Admissions",
    "features": "Đăng ký xét tuyển; học bổng; chương trình liên kết quốc tế",
    "language": "Vietnamese",
    "appFee": "Free",
    "deadlinePattern": "Per university",
    "notes": "International business focus"
  },
  {
    "name": "Cổng tuyển sinh SĐH ĐHQGHN",
    "baseUrl": "http://tssdh.vnu.edu.vn",
    "kind": "UNIVERSITY",
    "tier": "B",
    "fetchStrategy": "HTML",
    "country": "Vietnam",
    "category": "Postgraduate Admissions",
    "features": "Đăng ký online ThS/TS; nộp hồ sơ số; tra cứu kết quả; lệ phí 300k/500k; 2 đợt/năm; Zalo/hotline hỗ trợ",
    "language": "Vietnamese",
    "appFee": "300k (Master), 500k (PhD from Bachelor), 260k (PhD from Master)",
    "deadlinePattern": "Đợt 1: 3-4月; Đợt 2: 6-9月",
    "notes": "Centralized for 9 VNU member universities"
  },
  {
    "name": "Phòng ĐT SĐH ĐH KHTN ĐHQG HCM",
    "baseUrl": "https://sdh.hcmus.edu.vn",
    "kind": "UNIVERSITY",
    "tier": "B",
    "fetchStrategy": "HTML",
    "country": "Vietnam",
    "category": "Postgraduate Admissions",
    "features": "Đăng ký online; công bố kết quả; khung chương trình đào tạo; học phí",
    "language": "Vietnamese",
    "appFee": "Per program",
    "deadlinePattern": "Per program",
    "notes": "Top natural sciences university"
  },
  {
    "name": "Viện ĐT SĐH ĐH GTVT",
    "baseUrl": "https://sdh.ut.edu.vn",
    "kind": "UNIVERSITY",
    "tier": "B",
    "fetchStrategy": "HTML",
    "country": "Vietnam",
    "category": "Postgraduate Admissions",
    "features": "Đăng ký ThS/TS online; biểu mẫu; quy chế; tra cứu văn bằng",
    "language": "Vietnamese",
    "appFee": "Per program",
    "deadlinePattern": "Per program",
    "notes": "Transport focus"
  },
  {
    "name": "Khoa SĐH ĐH Lạc Hồng",
    "baseUrl": "https://tcnh.lhu.edu.vn",
    "kind": "UNIVERSITY",
    "tier": "B",
    "fetchStrategy": "HTML",
    "country": "Vietnam",
    "category": "Postgraduate Admissions",
    "features": "Thông báo tuyển sinh Tiến sĩ; chương trình đào tạo; học phí",
    "language": "Vietnamese",
    "appFee": "Per program",
    "deadlinePattern": "Per program",
    "notes": "Private university"
  },
  {
    "name": "Khoa SĐH ĐH Sư Phạm HN",
    "baseUrl": "https://sdh.ussh.vnu.edu.vn",
    "kind": "UNIVERSITY",
    "tier": "B",
    "fetchStrategy": "HTML",
    "country": "Vietnam",
    "category": "Postgraduate Admissions",
    "features": "Tuyển sinh ThS/TS 2 đợt/năm; quy trình online; học phí chi tiết",
    "language": "Vietnamese",
    "appFee": "300k (Master), 500k/260k (PhD)",
    "deadlinePattern": "Đợt 1: 3-4月; Đợt 2: 6-9月",
    "notes": "Humanities & Social Sciences focus"
  },
  {
    "name": "Phòng ĐT SĐH ĐH Ngoại Thương",
    "baseUrl": "https://sdh.ftu.edu.vn",
    "kind": "UNIVERSITY",
    "tier": "B",
    "fetchStrategy": "HTML",
    "country": "Vietnam",
    "category": "Postgraduate Admissions",
    "features": "Đăng ký ThS/TS; nhóm Zalo hỗ trợ; học phí; chương trình",
    "language": "Vietnamese",
    "appFee": "Per program",
    "deadlinePattern": "Per program",
    "notes": "International trade focus"
  },
  {
    "name": "Phòng ĐT SĐH ĐH Thái Nguyên",
    "baseUrl": "https://tnu.edu.vn/tuyen-sinh/sau-dai-hoc",
    "kind": "UNIVERSITY",
    "tier": "B",
    "fetchStrategy": "HTML",
    "country": "Vietnam",
    "category": "Postgraduate Admissions",
    "features": "Đề án tuyển sinh; chỉ tiêu; học phí; bổ sung chỉ tiêu",
    "language": "Vietnamese",
    "appFee": "Per program",
    "deadlinePattern": "Per program",
    "notes": "Regional university"
  },
  {
    "name": "Phòng ĐT SĐH ĐH Y Dược HN",
    "baseUrl": "https://sdh.hmu.edu.vn",
    "kind": "UNIVERSITY",
    "tier": "B",
    "fetchStrategy": "HTML",
    "country": "Vietnam",
    "category": "Postgraduate Admissions",
    "features": "Thông báo trúng tuyển; bảo vệ luận án; học phí; chuẩn đầu ra",
    "language": "Vietnamese",
    "appFee": "Per program",
    "deadlinePattern": "Per program",
    "notes": "Medical focus"
  },
  {
    "name": "Phòng ĐT SĐH ĐH Công Nghệ Thông Tin",
    "baseUrl": "https://tuyensinhsdh.uit.edu.vn",
    "kind": "UNIVERSITY",
    "tier": "B",
    "fetchStrategy": "HTML",
    "country": "Vietnam",
    "category": "Postgraduate Admissions",
    "features": "Nộp hồ sơ online 2026; chương trình đào tạo; hướng dẫn nộp hồ sơ",
    "language": "Vietnamese",
    "appFee": "Per program",
    "deadlinePattern": "Per program",
    "notes": "IT focus"
  },
  {
    "name": "Phòng ĐT SĐH ĐH Cần Thơ",
    "baseUrl": "https://gs.ctu.edu.vn",
    "kind": "UNIVERSITY",
    "tier": "B",
    "fetchStrategy": "HTML",
    "country": "Vietnam",
    "category": "Postgraduate Admissions",
    "features": "Tuyển sinh ThS/TS; học bổng; hợp tác quốc tế",
    "language": "Vietnamese",
    "appFee": "Per program",
    "deadlinePattern": "Per program",
    "notes": "Mekong Delta hub"
  },
  {
    "name": "Phòng ĐT SĐH ĐH Huế",
    "baseUrl": "https://grad.hueuni.edu.vn",
    "kind": "UNIVERSITY",
    "tier": "B",
    "fetchStrategy": "HTML",
    "country": "Vietnam",
    "category": "Postgraduate Admissions",
    "features": "Chương trình đào tạo; tuyển sinh; học bổng; quốc tế hóa",
    "language": "Vietnamese",
    "appFee": "Per program",
    "deadlinePattern": "Per program",
    "notes": "Central Vietnam hub"
  },
  {
    "name": "Phòng ĐT SĐH ĐH Đà Nẵng",
    "baseUrl": "https://gs.udn.vn",
    "kind": "UNIVERSITY",
    "tier": "B",
    "fetchStrategy": "HTML",
    "country": "Vietnam",
    "category": "Postgraduate Admissions",
    "features": "Thông tin tuyển sinh; học bổng; nghiên cứu khoa học",
    "language": "Vietnamese",
    "appFee": "Per program",
    "deadlinePattern": "Per program",
    "notes": "Central Vietnam hub"
  },
  {
    "name": "Phòng ĐT SĐH ĐH Quốc Gia TP.HCM",
    "baseUrl": "https://gs.vnuhcm.edu.vn",
    "kind": "UNIVERSITY",
    "tier": "B",
    "fetchStrategy": "HTML",
    "country": "Vietnam",
    "category": "Postgraduate Admissions",
    "features": "Hệ thống các trường thành viên; tuyển sinh tập trung",
    "language": "Vietnamese",
    "appFee": "Per program",
    "deadlinePattern": "Per program",
    "notes": "VNU-HCM graduate school"
  },
  {
    "name": "Trang tuyển sinh SĐH ĐH Kinh Tế TP.HCM",
    "baseUrl": "https://gs.ueh.edu.vn",
    "kind": "UNIVERSITY",
    "tier": "B",
    "fetchStrategy": "HTML",
    "country": "Vietnam",
    "category": "Postgraduate Admissions",
    "features": "Thạc sĩ tiếng Anh/tiếng Việt; MBA; học bổng; quốc tế",
    "language": "Vietnamese",
    "appFee": "Per program",
    "deadlinePattern": "Per program",
    "notes": "Large business university"
  },
  {
    "name": "Trang tuyển sinh SĐH ĐH Văn Hiến",
    "baseUrl": "https://sdh.vhu.edu.vn",
    "kind": "UNIVERSITY",
    "tier": "B",
    "fetchStrategy": "HTML",
    "country": "Vietnam",
    "category": "Postgraduate Admissions",
    "features": "Tuyển sinh tiến sĩ; điều kiện; hồ sơ; lịch thi",
    "language": "Vietnamese",
    "appFee": "Per program",
    "deadlinePattern": "Per program",
    "notes": "Private university"
  },
  {
    "name": "TopCV - Thực tập sinh",
    "baseUrl": "https://www.topcv.vn/tim-viec-lam-thuc-tap-sinh",
    "kind": "CORPORATE",
    "tier": "B",
    "fetchStrategy": "HTML",
    "country": "Vietnam",
    "category": "Internship & Jobs",
    "features": "1900+ việc làm; lọc theo ngành/lương/địa điểm; tạo CV miễn phí; verified employer",
    "language": "Vietnamese",
    "appFee": "Free for candidates",
    "deadlinePattern": "Continuous",
    "notes": "Largest job board; AI matching"
  },
  {
    "name": "VietnamWorks - Thực tập",
    "baseUrl": "https://www.vietnamworks.com/thuc-tap-sinh-kv",
    "kind": "CORPORATE",
    "tier": "B",
    "fetchStrategy": "HTML",
    "country": "Vietnam",
    "category": "Internship & Jobs",
    "features": "100+ việc làm; lương 5-6tr/tháng TB; bộ lọc nâng cao; career advice",
    "language": "Vietnamese/English",
    "appFee": "Free for candidates",
    "deadlinePattern": "Continuous",
    "notes": "Premium employer brand"
  },
  {
    "name": "CareerLink - Thực tập",
    "baseUrl": "https://www.careerlink.vn/viec-lam/thuc-tap",
    "kind": "CORPORATE",
    "tier": "B",
    "fetchStrategy": "HTML",
    "country": "Vietnam",
    "category": "Internship & Jobs",
    "features": "Việc làm 24h; CV online; matching AI; career fair",
    "language": "Vietnamese/English",
    "appFee": "Free for candidates",
    "deadlinePattern": "Continuous",
    "notes": "Strong tech focus"
  },
  {
    "name": "StudentJob.vn",
    "baseUrl": "https://studentjob.vn",
    "kind": "CORPORATE",
    "tier": "B",
    "fetchStrategy": "HTML",
    "country": "Vietnam",
    "category": "Internship & Jobs",
    "features": "Dành riêng SV: part-time, internship, freelance; Talent Network kết nối NTD",
    "language": "Vietnamese/English",
    "appFee": "Free",
    "deadlinePattern": "Continuous",
    "notes": "Student-focused platform"
  },
  {
    "name": "CareerViet - Internship",
    "baseUrl": "https://careerviet.vn/viec-lam/internship-k-vi.html",
    "kind": "CORPORATE",
    "tier": "B",
    "fetchStrategy": "HTML",
    "country": "Vietnam",
    "category": "Internship & Jobs",
    "features": "300+ internship; phân tích lương theo ngành; hướng dẫn ứng tuyển",
    "language": "Vietnamese",
    "appFee": "Free",
    "deadlinePattern": "Continuous",
    "notes": "Career analytics"
  },
  {
    "name": "JobOKO - Thực tập sinh",
    "baseUrl": "https://vn.joboko.com/tim-viec-lam-thuc-tap-sinh",
    "kind": "CORPORATE",
    "tier": "B",
    "fetchStrategy": "HTML",
    "country": "Vietnam",
    "category": "Internship & Jobs",
    "features": "3500+ việc làm; báo cáo lương 2026; phân biệt Intern/Trainee; top 7 vị trí HOT",
    "language": "Vietnamese",
    "appFee": "Free",
    "deadlinePattern": "Continuous",
    "notes": "Salary transparency"
  },
  {
    "name": "Internship.com.vn",
    "baseUrl": "https://internship.com.vn",
    "kind": "CORPORATE",
    "tier": "B",
    "fetchStrategy": "HTML",
    "country": "Vietnam",
    "category": "Internship & Jobs",
    "features": "Nền tảng toàn diện: review công ty, template CV/email/checklist, mentor, showcase dự án",
    "language": "Vietnamese",
    "appFee": "Freemium",
    "deadlinePattern": "Continuous",
    "notes": "Skill-building focus"
  },
  {
    "name": "Internship OneConnect (IOC)",
    "baseUrl": "https://ioc.rikkei.edu.vn",
    "kind": "CORPORATE",
    "tier": "B",
    "fetchStrategy": "HTML",
    "country": "Vietnam",
    "category": "Internship & Jobs",
    "features": "Thực tập thực chiến IT: mentor Tech Lead/PM, dự án AI/Automation, chứng chỉ OJT, mock interview",
    "language": "Vietnamese/English",
    "appFee": "Paid programs",
    "deadlinePattern": "Batch-based",
    "notes": "Tech-intensive; Rikkei Education"
  },
  {
    "name": "Trung tâm Hỗ trợ Sinh viên VN",
    "baseUrl": "https://vieclam.hoisinhvien.com.vn",
    "kind": "CORPORATE",
    "tier": "B",
    "fetchStrategy": "HTML",
    "country": "Vietnam",
    "category": "Internship & Jobs",
    "features": "Talent Network; việc làm theo ngành/địa điểm; cẩm nang contact NTD",
    "language": "Vietnamese",
    "appFee": "Free",
    "deadlinePattern": "Continuous",
    "notes": "Government-backed"
  },
  {
    "name": "Ybox.vn - Kỹ năng/Tuyển dụng",
    "baseUrl": "https://ybox.vn",
    "kind": "CORPORATE",
    "tier": "B",
    "fetchStrategy": "HTML",
    "country": "Vietnam",
    "category": "Internship & Jobs",
    "features": "Tổng hợp tin tuyển dụng, học bổng, sự kiện, chia sẻ nghề nghiệp, review công ty",
    "language": "Vietnamese",
    "appFee": "Free",
    "deadlinePattern": "Continuous",
    "notes": "Community-driven"
  },
  {
    "name": "MyWork.com.vn",
    "baseUrl": "https://mywork.com.vn",
    "kind": "CORPORATE",
    "tier": "B",
    "fetchStrategy": "HTML",
    "country": "Vietnam",
    "category": "Internship & Jobs",
    "features": "Tạo hồ sơ online miễn phí; tìm việc thực tập; mẫu CV/đơn xin việc",
    "language": "Vietnamese",
    "appFee": "Free",
    "deadlinePattern": "Continuous",
    "notes": "Simple interface"
  },
  {
    "name": "Tuyendung.com.vn",
    "baseUrl": "https://tuyendung.com.vn",
    "kind": "CORPORATE",
    "tier": "B",
    "fetchStrategy": "HTML",
    "country": "Vietnam",
    "category": "Internship & Jobs",
    "features": "Khối việc làm lớn; mẫu CV/đơn; kỹ năng phỏng vấn; quản trị nhân sự",
    "language": "Vietnamese",
    "appFee": "Free for candidates",
    "deadlinePattern": "Continuous",
    "notes": "HR resource hub"
  },
  {
    "name": "Học bổng cho sinh viên",
    "baseUrl": "https://www.hocbongchosinhvien.com",
    "kind": "NGO",
    "tier": "B",
    "fetchStrategy": "HTML",
    "country": "Vietnam",
    "category": "Scholarships",
    "features": "Tổng hợp học bổng doanh nghiệp, quỹ từ thiện, du học; cập nhật liên tục",
    "language": "Vietnamese",
    "appFee": "Free",
    "deadlinePattern": "Continuous",
    "notes": "Aggregator portal"
  },
  {
    "name": "VietEdu24h - Học bổng DN",
    "baseUrl": "https://vietedu24h.edu.vn/hoc-bong-doanh-nghiep",
    "kind": "NGO",
    "tier": "B",
    "fetchStrategy": "HTML",
    "country": "Vietnam",
    "category": "Scholarships",
    "features": "Phân loại: du học, doanh nghiệp, tu nghiệp; đa ngôn ngữ (VI/EN)",
    "language": "Vietnamese/English",
    "appFee": "Free",
    "deadlinePattern": "Continuous",
    "notes": "Study abroad agency"
  },
  {
    "name": "Trung tâm Đối mới Sáng tạo NEU",
    "baseUrl": "https://jobs.neu.edu.vn/categories/hoc-bong-doanh-nghiep",
    "kind": "NGO",
    "tier": "B",
    "fetchStrategy": "HTML",
    "country": "Vietnam",
    "category": "Scholarships",
    "features": "Học bổng VPBank, Sacombank, MB, DB Dream Leader; bài viết hướng dẫn viết bài luận",
    "language": "Vietnamese",
    "appFee": "Free",
    "deadlinePattern": "Per scholarship",
    "notes": "University career center"
  },
  {
    "name": "SCG Sharing The Dream",
    "baseUrl": "https://scg.sac.vn",
    "kind": "NGO",
    "tier": "B",
    "fetchStrategy": "HTML",
    "country": "Vietnam",
    "category": "Scholarships",
    "features": "Học bổng 2-4 khóa/năm; dự án cộng đồng; thực tập tại nhà máy SCG; duy trì 20 suất/năm",
    "language": "Vietnamese/English",
    "appFee": "Free",
    "deadlinePattern": "Annual (around Q1)",
    "notes": "Corporate scholarship (industrial group)"
  },
  {
    "name": "Quỹ Học bổng Vingroup (VinUni)",
    "baseUrl": "https://scholarships.vinuni.edu.vn",
    "kind": "NGO",
    "tier": "B",
    "fetchStrategy": "HTML",
    "country": "Vietnam",
    "category": "Scholarships",
    "features": "Học bổng toàn phần ThS/TS du học (học phí + trợ cấp + bảo hiểm + visa); tiêu chí AACC",
    "language": "Vietnamese/English",
    "appFee": "Free",
    "deadlinePattern": "Annual",
    "notes": "Prestigious full-ride for grad studies abroad"
  },
  {
    "name": "Quỹ Khuyến học Giáo dục Việt (WINGO)",
    "baseUrl": "https://duhocwingo.edu.vn",
    "kind": "NGO",
    "tier": "B",
    "fetchStrategy": "HTML",
    "country": "Vietnam",
    "category": "Scholarships",
    "features": "100% học phí FDI; trợ cấp 6-12tr/tháng; BHXH; việc làm sau TN; ngành kỹ thuật/CN",
    "language": "Vietnamese",
    "appFee": "Free",
    "deadlinePattern": "Annual",
    "notes": "FDI-backed vocational scholarship"
  },
  {
    "name": "Học bổng EAS Việt Nam",
    "baseUrl": "https://www.easvietnam.edu.vn",
    "kind": "NGO",
    "tier": "B",
    "fetchStrategy": "HTML",
    "country": "Vietnam",
    "category": "Scholarships",
    "features": "9 loại học bổng (GLS, IPS, MIC, YLP, IIS, BNI, GES, NRE); đào tạo quản trị toàn cầu",
    "language": "Vietnamese/English",
    "appFee": "Free",
    "deadlinePattern": "Per program",
    "notes": "Leadership development focus"
  },
  {
    "name": "Gamuda Land Scholarship",
    "baseUrl": "https://gamudalandvietnam.vn",
    "kind": "NGO",
    "tier": "B",
    "fetchStrategy": "HTML",
    "country": "Vietnam",
    "category": "Scholarships",
    "features": "Toàn phần 1.5 tỷ đồng; thực tập tại Gamuda; mentor lãnh đạo",
    "language": "Vietnamese/English",
    "appFee": "Free",
    "deadlinePattern": "Annual",
    "notes": "Property developer scholarship"
  },
  {
    "name": "Học bổng TOTO Việt Nam",
    "baseUrl": "https://qldt.ftu.edu.vn",
    "kind": "NGO",
    "tier": "B",
    "fetchStrategy": "HTML",
    "country": "Vietnam",
    "category": "Scholarships",
    "features": "6 suất 5tr/suất/năm cho sinh viên FTU; đăng ký Google Form",
    "language": "Vietnamese",
    "appFee": "Free",
    "deadlinePattern": "Annual",
    "notes": "Corporate (Japanese JV)"
  },
  {
    "name": "Học bổng Vietcombank",
    "baseUrl": "https://fbm.neu.edu.vn",
    "kind": "NGO",
    "tier": "B",
    "fetchStrategy": "HTML",
    "country": "Vietnam",
    "category": "Scholarships",
    "features": "Học bổng ngân hàng; mẫu đơn online; nộp qua Forms Office",
    "language": "Vietnamese",
    "appFee": "Free",
    "deadlinePattern": "Annual",
    "notes": "Bank scholarship"
  },
  {
    "name": "Quỹ Thắp Sáng Niềm Tin (PVcomBank)",
    "baseUrl": "https://www.pvcombank.com.vn",
    "kind": "NGO",
    "tier": "B",
    "fetchStrategy": "HTML",
    "country": "Vietnam",
    "category": "Scholarships",
    "features": "110 suất/năm; 18 năm hoạt động; 1600+ SV được hỗ trợ; phỏng vấn trực tuyến",
    "language": "Vietnamese",
    "appFee": "Free",
    "deadlinePattern": "Annual",
    "notes": "Long-running bank foundation"
  },
  {
    "name": "Học bổng Hoa Sen (HSU)",
    "baseUrl": "https://www.hoasen.edu.vn",
    "kind": "NGO",
    "tier": "B",
    "fetchStrategy": "HTML",
    "country": "Vietnam",
    "category": "Scholarships",
    "features": "15% học phí toàn khóa (duy trì); nhiều loại HB khác lên đến 70%",
    "language": "Vietnamese",
    "appFee": "Free",
    "deadlinePattern": "Per intake",
    "notes": "Private university scholarship"
  },
  {
    "name": "EducationUSA",
    "baseUrl": "https://educationusa.state.gov",
    "kind": "GOVERNMENT",
    "tier": "A",
    "fetchStrategy": "HTML",
    "country": "USA",
    "category": "Undergraduate Admissions",
    "features": "Nguồn chính thức Bộ Ngoại giao Mỹ; 430+ trung tâm tư vấn; 5 bước du học Mỹ; tìm trường/học bổng/visa",
    "language": "English",
    "appFee": "Free",
    "deadlinePattern": "Continuous",
    "notes": "Official US government source"
  },
  {
    "name": "Common App",
    "baseUrl": "https://www.commonapp.org",
    "kind": "PORTAL",
    "tier": "A",
    "fetchStrategy": "HTML",
    "country": "USA",
    "category": "Undergraduate Admissions",
    "features": "Nộp đơn 1 lần cho 1000+ trường ĐH Mỹ; quản lý deadline, essay, recommendation letter",
    "language": "English",
    "appFee": "Per university ($50-100 typical)",
    "deadlinePattern": "Nov 1 (EA/ED), Jan 1 (RD)",
    "notes": "Centralized application platform"
  },
  {
    "name": "College Board",
    "baseUrl": "https://www.collegeboard.org",
    "kind": "UNIVERSITY",
    "tier": "B",
    "fetchStrategy": "HTML",
    "country": "USA",
    "category": "Undergraduate Admissions",
    "features": "Đăng ký SAT/AP; tìm trường/học bổng; CSS Profile (financial aid); BigFuture college search",
    "language": "English",
    "appFee": "SAT $60, CSS Profile $25",
    "deadlinePattern": "Test dates: Mar, May, Jun, Aug, Oct, Dec",
    "notes": "Testing & college search"
  },
  {
    "name": "Fastweb",
    "baseUrl": "https://www.fastweb.com",
    "kind": "PORTAL",
    "tier": "B",
    "fetchStrategy": "HTML",
    "country": "USA",
    "category": "Scholarships",
    "features": "Cơ sở dữ liệu học bổng lớn; match theo profile cá nhân; part-time job; internship",
    "language": "English",
    "appFee": "Free",
    "deadlinePattern": "Continuous",
    "notes": "Profile-based matching"
  },
  {
    "name": "Scholarships.com",
    "baseUrl": "https://www.scholarships.com",
    "kind": "PORTAL",
    "tier": "B",
    "fetchStrategy": "HTML",
    "country": "USA",
    "category": "Scholarships",
    "features": "Tìm học bổng theo profile; loại bỏ không phù hợp; financial aid calculator",
    "language": "English",
    "appFee": "Free",
    "deadlinePattern": "Continuous",
    "notes": "Personalized matching"
  },
  {
    "name": "InternationalStudent.com",
    "baseUrl": "https://www.internationalstudent.com",
    "kind": "PORTAL",
    "tier": "B",
    "fetchStrategy": "HTML",
    "country": "USA",
    "category": "Scholarships",
    "features": "Scholarship search; study guides theo bang; loan programs; featured schools",
    "language": "English",
    "appFee": "Free",
    "deadlinePattern": "Continuous",
    "notes": "International student focus"
  },
  {
    "name": "IEFA",
    "baseUrl": "https://www.iefa.org",
    "kind": "NGO",
    "tier": "B",
    "fetchStrategy": "HTML",
    "country": "USA",
    "category": "Scholarships",
    "features": "Premier resource cho international scholarship/grant; loan programs; state guides",
    "language": "English",
    "appFee": "Free",
    "deadlinePattern": "Continuous",
    "notes": "Comprehensive database"
  },
  {
    "name": "InternationalScholarships.com",
    "baseUrl": "https://www.internationalscholarships.com",
    "kind": "PORTAL",
    "tier": "B",
    "fetchStrategy": "HTML",
    "country": "USA",
    "category": "Scholarships",
    "features": "Comprehensive listing grants/scholarships/loans; contact award administrators",
    "language": "English",
    "appFee": "Free",
    "deadlinePattern": "Continuous",
    "notes": "Direct contact info for registered users"
  },
  {
    "name": "UCAS",
    "baseUrl": "https://www.ucas.com",
    "kind": "PORTAL",
    "tier": "A",
    "fetchStrategy": "HTML",
    "country": "UK",
    "category": "Undergraduate Admissions",
    "features": "Hệ thống tập trung: 380+ trường; 5 choices; personal statement; tracking; Clearing; document upload (2027); agent portal",
    "language": "English",
    "appFee": "£27.50 (2025 entry)",
    "deadlinePattern": "15 Oct (Oxbridge/Med), 29 Jan (main), 30 Jun (late)",
    "notes": "UK national admissions service"
  },
  {
    "name": "UCAS International",
    "baseUrl": "https://international.ucas.com",
    "kind": "PORTAL",
    "tier": "A",
    "fetchStrategy": "HTML",
    "country": "UK",
    "category": "Undergraduate Admissions",
    "features": "Hướng dẫn riêng SV quốc tế: visa, English test, qualification recognition; 150k+ applicants/năm",
    "language": "English",
    "appFee": "Same as UCAS",
    "deadlinePattern": "Same as UCAS",
    "notes": "Dedicated international support"
  },
  {
    "name": "Study UK (British Council)",
    "baseUrl": "https://study-uk.britishcouncil.org",
    "kind": "NGO",
    "tier": "B",
    "fetchStrategy": "HTML",
    "country": "UK",
    "category": "Scholarships & Info",
    "features": "Tìm khóa học; học bổng (Chevening, GREAT); visa; life in UK; events",
    "language": "English",
    "appFee": "Free",
    "deadlinePattern": "Per scholarship",
    "notes": "Official UK promotion body"
  },
  {
    "name": "The Student Room",
    "baseUrl": "https://www.thestudentroom.co.uk",
    "kind": "UNIVERSITY",
    "tier": "B",
    "fetchStrategy": "HTML",
    "country": "UK",
    "category": "Community & Info",
    "features": "Forum lớn nhất UK: review trường; personal statement help; interview tips; clearing advice",
    "language": "English",
    "appFee": "Free",
    "deadlinePattern": "Continuous",
    "notes": "Peer support community"
  },
  {
    "name": "Prospects.ac.uk",
    "baseUrl": "https://www.prospects.ac.uk",
    "kind": "UNIVERSITY",
    "tier": "B",
    "fetchStrategy": "HTML",
    "country": "UK",
    "category": "Career & Postgrad",
    "features": "Career guidance; postgraduate search; job sectors; work experience; internships UK",
    "language": "English",
    "appFee": "Free",
    "deadlinePattern": "Continuous",
    "notes": "Graduate career focus"
  },
  {
    "name": "DAAD",
    "baseUrl": "https://www.daad.de",
    "kind": "GOVERNMENT",
    "tier": "A",
    "fetchStrategy": "HTML",
    "country": "Germany",
    "category": "Undergraduate Admissions",
    "features": "Database 21k+ chương trình; admission database (140 quốc gia); scholarship database; My GUIDE; TestAS; Student Journey",
    "language": "English/German",
    "appFee": "Free",
    "deadlinePattern": "Continuous",
    "notes": "Largest academic exchange org"
  },
  {
    "name": "Study in Germany",
    "baseUrl": "https://www.study-in-germany.de",
    "kind": "UNIVERSITY",
    "tier": "B",
    "fetchStrategy": "HTML",
    "country": "Germany",
    "category": "Undergraduate Admissions",
    "features": "Plan studies; find programs; prepare stay; discover cities; scholarship info",
    "language": "English/German",
    "appFee": "Free",
    "deadlinePattern": "Continuous",
    "notes": "Official DAAD portal"
  },
  {
    "name": "Hochschulkompass (HRK)",
    "baseUrl": "https://www.hochschulkompass.de",
    "kind": "UNIVERSITY",
    "tier": "B",
    "fetchStrategy": "HTML",
    "country": "Germany",
    "category": "Undergraduate Admissions",
    "features": "Database chương trình của Hội Hiệu trưởng ĐH Đức; admission requirements",
    "language": "German/English",
    "appFee": "Free",
    "deadlinePattern": "Continuous",
    "notes": "University rectorate database"
  },
  {
    "name": "uni-assist",
    "baseUrl": "https://www.uni-assist.de",
    "kind": "PORTAL",
    "tier": "A",
    "fetchStrategy": "HTML",
    "country": "Germany",
    "category": "Application Processing",
    "features": "Xử lý hồ sơ SV quốc tế cho 180+ ĐH Đức; preliminary review (VPD); 75€ fee",
    "language": "English/German",
    "appFee": "€75 (first), €30 (additional)",
    "deadlinePattern": "Per semester deadlines",
    "notes": "Competence center for int'l certificates"
  },
  {
    "name": "Hochschulstart",
    "baseUrl": "https://www.hochschulstart.de",
    "kind": "PORTAL",
    "tier": "A",
    "fetchStrategy": "HTML",
    "country": "Germany",
    "category": "Restricted Programs",
    "features": "Xét tuyển tập trung y/dược/súc vật; Stiftung für Hochschulzulassung",
    "language": "German",
    "appFee": "Free",
    "deadlinePattern": "Specific deadlines",
    "notes": "Medicine/pharmacy/vet only"
  },
  {
    "name": "Study Australia (Gov)",
    "baseUrl": "https://www.studyaustralia.gov.au",
    "kind": "GOVERNMENT",
    "tier": "A",
    "fetchStrategy": "HTML",
    "country": "Australia",
    "category": "Undergraduate Admissions",
    "features": "5 bước du học Úc; course search tool; cost estimator; visa guide; OSHC",
    "language": "English",
    "appFee": "Free",
    "deadlinePattern": "Continuous",
    "notes": "Official Australian gov portal"
  },
  {
    "name": "Study in Australia (Top Universities)",
    "baseUrl": "https://www.topuniversities.com/where-to-study/oceania/australia/guide",
    "kind": "UNIVERSITY",
    "tier": "B",
    "fetchStrategy": "HTML",
    "country": "Australia",
    "category": "Undergraduate Admissions",
    "features": "Hướng dẫn admission Úc; visa subclass 500; eCoE; Genuine Student requirement",
    "language": "English",
    "appFee": "Free",
    "deadlinePattern": "Continuous",
    "notes": "QS ranking guide"
  },
  {
    "name": "VTAC",
    "baseUrl": "https://www.vtac.edu.au",
    "kind": "PORTAL",
    "tier": "A",
    "fetchStrategy": "HTML",
    "country": "Australia",
    "category": "Application Processing",
    "features": "Hệ thống đăng ký tập trung Victoria (Melbourne); cho Year 12/IB trong nước",
    "language": "English",
    "appFee": "~AUD $40-120",
    "deadlinePattern": "Aug - Sep (Year 12)",
    "notes": "Victoria state only"
  },
  {
    "name": "UAC",
    "baseUrl": "https://www.uac.edu.au",
    "kind": "PORTAL",
    "tier": "A",
    "fetchStrategy": "HTML",
    "country": "Australia",
    "category": "Application Processing",
    "features": "Hệ thống đăng ký tập trung NSW/ACT (Sydney); international Year 12/IB",
    "language": "English",
    "appFee": "~AUD $70-200",
    "deadlinePattern": "Aug - Sep (Year 12)",
    "notes": "NSW/ACT state only"
  },
  {
    "name": "QTAC",
    "baseUrl": "https://www.qtac.edu.au",
    "kind": "PORTAL",
    "tier": "A",
    "fetchStrategy": "HTML",
    "country": "Australia",
    "category": "Application Processing",
    "features": "Hệ thống đăng ký tập trung Queensland (Brisbane)",
    "language": "English",
    "appFee": "~AUD $50-150",
    "deadlinePattern": "Aug - Sep (Year 12)",
    "notes": "Queensland state only"
  },
  {
    "name": "Studielink",
    "baseUrl": "https://www.studielink.nl",
    "kind": "PORTAL",
    "tier": "A",
    "fetchStrategy": "HTML",
    "country": "Netherlands",
    "category": "Undergraduate Admissions",
    "features": "Portal quốc gia duy nhất; enrolment 4 programs/năm; numerus fixus deadline 15/1; regular 1/5; DigiD/non-DigiD",
    "language": "English/Dutch",
    "appFee": "Free",
    "deadlinePattern": "15 Jan (numerus fixus), 1 May (regular)",
    "notes": "Mandatory for all Dutch higher ed"
  },
  {
    "name": "Study in Holland (Nuffic)",
    "baseUrl": "https://www.studyinnl.org",
    "kind": "UNIVERSITY",
    "tier": "B",
    "fetchStrategy": "HTML",
    "country": "Netherlands",
    "category": "Undergraduate Admissions",
    "features": "Official info: how to apply; deadlines; scholarships (Holland Scholarship); visa; housing",
    "language": "English/Dutch",
    "appFee": "Free",
    "deadlinePattern": "Continuous",
    "notes": "Nuffic official portal"
  },
  {
    "name": "University of Groningen Progress Portal",
    "baseUrl": "https://www.rug.nl/education/application-enrolment-tuition-fees",
    "kind": "UNIVERSITY",
    "tier": "B",
    "fetchStrategy": "HTML",
    "country": "Netherlands",
    "category": "Undergraduate Admissions",
    "features": "Application fee €100; Early Bird deadline 28/2; document upload; certified copies",
    "language": "English",
    "appFee": "€100 (non-EU)",
    "deadlinePattern": "1 May (regular), 15 Jan (numerus fixus)",
    "notes": "Top research university"
  },
  {
    "name": "Leiden University uSis",
    "baseUrl": "https://www.universiteitleiden.nl/en/education/admission-and-application",
    "kind": "UNIVERSITY",
    "tier": "B",
    "fetchStrategy": "HTML",
    "country": "Netherlands",
    "category": "Undergraduate Admissions",
    "features": "Application fee €100; Studielink → uSis; exemptions; Prepare your stay",
    "language": "English",
    "appFee": "€100 (non-EU)",
    "deadlinePattern": "15 Jan (numerus fixus), 1 May (regular)",
    "notes": "Oldest Dutch university"
  },
  {
    "name": "Study in Japan (MEXT/JASSO)",
    "baseUrl": "https://www.studyinjapan.go.jp",
    "kind": "GOVERNMENT",
    "tier": "A",
    "fetchStrategy": "HTML",
    "country": "Japan",
    "category": "Scholarships & Admissions",
    "features": "Portal chính thức: MEXT scholarship (7 loại); JASSO Honors; EJU exam; Japan Education Fairs",
    "language": "English/Japanese",
    "appFee": "Free",
    "deadlinePattern": "Continuous",
    "notes": "Official Japanese gov portal"
  },
  {
    "name": "JASSO Scholarships",
    "baseUrl": "https://www.jasso.go.jp/en/ryugaku/scholarship_j",
    "kind": "GOVERNMENT",
    "tier": "A",
    "fetchStrategy": "HTML",
    "country": "Japan",
    "category": "Scholarships",
    "features": "Monbukagakusho Honors (48k JPY/tháng); Reservation Program (EJU/Pre-arrival); Student Exchange Support (80k JPY/tháng)",
    "language": "English/Japanese",
    "appFee": "Free",
    "deadlinePattern": "EJU: Jun/Nov; Reservation: varies",
    "notes": "Japan Student Services Organization"
  },
  {
    "name": "MEXT Scholarship",
    "baseUrl": "https://www.mext.go.jp/en/policy/education/highered/title02/detail02/sdetail02/1373897.htm",
    "kind": "GOVERNMENT",
    "tier": "A",
    "fetchStrategy": "HTML",
    "country": "Japan",
    "category": "Scholarships",
    "features": "7 loại: Research, Teacher training, Undergraduate, Japanese studies, College of technology, Specialized training, YLP; Embassy/University recommendation",
    "language": "English/Japanese",
    "appFee": "Free",
    "deadlinePattern": "Embassy: Apr-May; University: varies",
    "notes": "Ministry of Education, Culture, Sports, Science and Technology"
  },
  {
    "name": "Tohoku University Scholarships",
    "baseUrl": "https://www.insc.tohoku.ac.jp/english/scholarship-for-international-students",
    "kind": "NGO",
    "tier": "B",
    "fetchStrategy": "HTML",
    "country": "Japan",
    "category": "Scholarships",
    "features": "Bảng so sánh: MEXT (Embassy/Univ); JASSO Reservation/General; University Excellence; Private Foundation",
    "language": "English/Japanese",
    "appFee": "Free",
    "deadlinePattern": "Per scholarship",
    "notes": "Top national university"
  },
  {
    "name": "Tokyo Tech (Science Tokyo) JASSO",
    "baseUrl": "https://www.titech.ac.jp/english/student-support/prospective-students/scholarships/jasso",
    "kind": "GOVERNMENT",
    "tier": "A",
    "fetchStrategy": "HTML",
    "country": "Japan",
    "category": "Scholarships",
    "features": "Pre-arrival reservation (GSEP/IGP); EJU reservation; qualification criteria chi tiết",
    "language": "English/Japanese",
    "appFee": "Free",
    "deadlinePattern": "Per scholarship",
    "notes": "Top tech university"
  },
  {
    "name": "Study in Korea (NIIED)",
    "baseUrl": "https://www.studyinkorea.go.kr",
    "kind": "GOVERNMENT",
    "tier": "A",
    "fetchStrategy": "HTML",
    "country": "South Korea",
    "category": "Scholarships & Admissions",
    "features": "Portal chính thức chính phủ Hàn: GKS; university info; visa; life in Korea",
    "language": "English/Korean",
    "appFee": "Free",
    "deadlinePattern": "Continuous",
    "notes": "National Institute for International Education"
  },
  {
    "name": "GKS (Global Korea Scholarship)",
    "baseUrl": "https://www.studyinkorea.go.kr/in/plan/scholarship.do",
    "kind": "GOVERNMENT",
    "tier": "A",
    "fetchStrategy": "HTML",
    "country": "South Korea",
    "category": "Scholarships",
    "features": "Embassy Track (General/R-GKS/Overseas Koreans) & University Track (UIC/Associate); 280 CĐ/ĐH + 1600 ThS/TS; TOPIK exemption; online application",
    "language": "English/Korean",
    "appFee": "Free",
    "deadlinePattern": "Embassy: Sep 15-30; University: Sep-Nov",
    "notes": "Full funding: tuition + stipend + airfare + insurance"
  },
  {
    "name": "NIIED GKS Degree Program",
    "baseUrl": "https://www.niied.go.kr/web/niied/contents/niiedEng/eng_gksDegree",
    "kind": "GOVERNMENT",
    "tier": "A",
    "fetchStrategy": "HTML",
    "country": "South Korea",
    "category": "Scholarships",
    "features": "Chi tiết qualification; selection rounds (4 rounds embassy, 2 rounds university); timeline; contact",
    "language": "English/Korean",
    "appFee": "Free",
    "deadlinePattern": "Annual cycle",
    "notes": "Official guidelines"
  },
  {
    "name": "POSTECH GKS-UIC",
    "baseUrl": "https://adm-iu.postech.ac.kr/user/admission/guide/gks.do",
    "kind": "GOVERNMENT",
    "tier": "A",
    "fetchStrategy": "HTML",
    "country": "South Korea",
    "category": "Scholarships",
    "features": "GKS-UIC: industry cooperation; internship; IT-focused; pre-arranged placement; 1M won/tháng",
    "language": "English/Korean",
    "appFee": "Free",
    "deadlinePattern": "Per university",
    "notes": "Top tech university partnership"
  },
  {
    "name": "NUS Admissions",
    "baseUrl": "https://www.nus.edu.sg/oam/admissions",
    "kind": "UNIVERSITY",
    "tier": "B",
    "fetchStrategy": "HTML",
    "country": "Singapore",
    "category": "Undergraduate Admissions",
    "features": "6 applicant groups; Applicant Portal (Singpass/social login); Tuition Grant (3-year bond); S$20 fee; interview/selection tests",
    "language": "English",
    "appFee": "S$20 (int'l)",
    "deadlinePattern": "Dec - Mar (varies by qualification)",
    "notes": "Top ranked Asian university"
  },
  {
    "name": "NTU Admissions",
    "baseUrl": "https://www.ntu.edu.sg/admissions/undergraduate",
    "kind": "UNIVERSITY",
    "tier": "B",
    "fetchStrategy": "HTML",
    "country": "Singapore",
    "category": "Undergraduate Admissions",
    "features": "Check Status portal; document upload (JPG/PDF ≤5MB); application fee SGD$25; interview shortlist; Art/Design portfolio",
    "language": "English",
    "appFee": "SGD$25 (int'l)",
    "deadlinePattern": "Oct - Mar (varies)",
    "notes": "Top ranked Asian university"
  },
  {
    "name": "SMU Admissions",
    "baseUrl": "https://admissions.smu.edu.sg",
    "kind": "UNIVERSITY",
    "tier": "B",
    "fetchStrategy": "HTML",
    "country": "Singapore",
    "category": "Undergraduate Admissions",
    "features": "Standardised test required (SAT 1350/ACT 29/IELTS 7.0); interview (Law: writing test); fee SGD$15; criminal records declaration",
    "language": "English",
    "appFee": "SGD$15",
    "deadlinePattern": "Nov - Mar",
    "notes": "Business/management focus"
  },
  {
    "name": "SUTD Admissions",
    "baseUrl": "https://www.sutd.edu.sg/admissions/undergraduate",
    "kind": "UNIVERSITY",
    "tier": "B",
    "fetchStrategy": "HTML",
    "country": "Singapore",
    "category": "Undergraduate Admissions",
    "features": "Focus Math/Science; MTL requirement; English proficiency compulsory cho non-English medium; IB/UEC/STPM/India/Vietnam specific",
    "language": "English",
    "appFee": "Free",
    "deadlinePattern": "Nov - Mar",
    "notes": "Design & technology focus"
  },
  {
    "name": "CampusArt (France in SG)",
    "baseUrl": "https://www.campusfrance.org/en/campusart",
    "kind": "GOVERNMENT",
    "tier": "A",
    "fetchStrategy": "HTML",
    "country": "Singapore",
    "category": "Arts Admissions",
    "features": "Art/design/fashion/music/architecture applications; jury selection; shared platform",
    "language": "English/French",
    "appFee": "Free",
    "deadlinePattern": "Per program",
    "notes": "French cultural diplomacy"
  },
  {
    "name": "Study in Canada (Gov)",
    "baseUrl": "https://www.canada.ca/en/immigration-refugees-citizenship/services/study-canada.html",
    "kind": "UNIVERSITY",
    "tier": "B",
    "fetchStrategy": "HTML",
    "country": "Canada",
    "category": "Undergraduate Admissions",
    "features": "Official: study permit; choose school; work while/after study; extend permit",
    "language": "English/French",
    "appFee": "Free",
    "deadlinePattern": "Continuous",
    "notes": "Official Canadian gov portal"
  },
  {
    "name": "EduCanada",
    "baseUrl": "https://www.educanada.ca",
    "kind": "UNIVERSITY",
    "tier": "B",
    "fetchStrategy": "HTML",
    "country": "Canada",
    "category": "Program Search",
    "features": "Program search tool; cost calculator; map; recruitment events; common pathways",
    "language": "English/French",
    "appFee": "Free",
    "deadlinePattern": "Continuous",
    "notes": "Official promotion portal"
  },
  {
    "name": "OUAC (Ontario)",
    "baseUrl": "https://www.ouac.on.ca",
    "kind": "PORTAL",
    "tier": "A",
    "fetchStrategy": "HTML",
    "country": "Canada",
    "category": "Application Processing",
    "features": "Centralized application cho 21 ĐH Ontario; international students apply here",
    "language": "English",
    "appFee": "~CAD $150-200",
    "deadlinePattern": "Jan (main), varies by program",
    "notes": "Ontario province only"
  },
  {
    "name": "University of Toronto International",
    "baseUrl": "https://future.utoronto.ca/international-students",
    "kind": "UNIVERSITY",
    "tier": "B",
    "fetchStrategy": "HTML",
    "country": "Canada",
    "category": "Undergraduate Admissions",
    "features": "30% SV quốc tế; guaranteed residence; 2-step: OUAC → applicant portal",
    "language": "English",
    "appFee": "OUAC fee + $180 supplement",
    "deadlinePattern": "OUAC deadlines",
    "notes": "Top Canadian university"
  },
  {
    "name": "University of Alberta International",
    "baseUrl": "https://www.ualberta.ca/en/admissions/how-to-apply/international-students-in-canada.html",
    "kind": "UNIVERSITY",
    "tier": "B",
    "fetchStrategy": "HTML",
    "country": "Canada",
    "category": "Undergraduate Admissions",
    "features": "Automatic scholarships (Gold Standard $6k, Int'l Admission $5k); application-based (President's $120k); tuition guarantee",
    "language": "English",
    "appFee": "CAD $125",
    "deadlinePattern": "Mar 1 (documents)",
    "notes": "Strong scholarship program"
  },
  {
    "name": "York University International",
    "baseUrl": "https://futurestudents.yorku.ca/your-application/how-apply/international-student",
    "kind": "UNIVERSITY",
    "tier": "B",
    "fetchStrategy": "HTML",
    "country": "Canada",
    "category": "Undergraduate Admissions",
    "features": "Country-specific requirements (US: SAT 1170/ACT 24); Supplementary Form; 10k+ int'l students",
    "language": "English",
    "appFee": "CAD $130",
    "deadlinePattern": "Feb - Jun (varies)",
    "notes": "Large international population"
  },
  {
    "name": "Campus France",
    "baseUrl": "https://www.campusfrance.org",
    "kind": "GOVERNMENT",
    "tier": "A",
    "fetchStrategy": "HTML",
    "country": "France",
    "category": "Undergraduate Admissions",
    "features": "Portal chính thức: Etudes en France (73 quốc gia); DAP/HDAP; TCF/DELF/DALF; 50k+ programs; Programs in English (1600+)",
    "language": "English/French",
    "appFee": "Free",
    "deadlinePattern": "Continuous",
    "notes": "Official French gov agency"
  },
  {
    "name": "Etudes en France",
    "baseUrl": "https://www.etudes-en-france.fr",
    "kind": "PORTAL",
    "tier": "A",
    "fetchStrategy": "HTML",
    "country": "France",
    "category": "Application Processing",
    "features": "Platform 100% digital: create account; apply 3 (DAP) / 7 (HDAP) programs; pay fee; interview; visa pre-consular file",
    "language": "English/French",
    "appFee": "€280 (DAP/HDAP)",
    "deadlinePattern": "Oct 1 - Dec 15 (DAP); Oct 1 - Feb 15 (HDAP)",
    "notes": "Mandatory for 73 countries including Vietnam"
  },
  {
    "name": "Parcoursup",
    "baseUrl": "https://www.parcoursup.fr",
    "kind": "PORTAL",
    "tier": "A",
    "fetchStrategy": "HTML",
    "country": "France",
    "category": "Undergraduate Admissions",
    "features": "Admission tập trung 1re année licence (EU citizens + French/Euro bac holders); wish formulation Dec-Mar",
    "language": "French",
    "appFee": "Free",
    "deadlinePattern": "Jan - Mar",
    "notes": "French/EU baccalaureate holders"
  },
  {
    "name": "Mon Master",
    "baseUrl": "https://www.monmaster.gouv.fr",
    "kind": "UNIVERSITY",
    "tier": "B",
    "fetchStrategy": "HTML",
    "country": "France",
    "category": "Postgraduate Admissions",
    "features": "National platform cho Master admission (EU/EEA residents + non-Etudes en France countries)",
    "language": "French",
    "appFee": "Free",
    "deadlinePattern": "Feb - Mar",
    "notes": "Master's degree centralized"
  },
  {
    "name": "Universitaly",
    "baseUrl": "https://www.universitaly.it",
    "kind": "UNIVERSITY",
    "tier": "B",
    "fetchStrategy": "HTML",
    "country": "Italy",
    "category": "Undergraduate Admissions",
    "features": "Portal duy nhất MUR: pre-enrollment mandatory cho visa; 10 steps; CIMEA/DoV validation; Italian language B2 test; GOMP student account",
    "language": "English/Italian",
    "appFee": "Free",
    "deadlinePattern": "Pre-enrollment by Sep 15; Visa by Nov 30",
    "notes": "Ministry of University and Research official portal"
  },
  {
    "name": "Universitaly Foreign Students",
    "baseUrl": "https://www.universitaly.it/en/studenti-stranieri",
    "kind": "UNIVERSITY",
    "tier": "B",
    "fetchStrategy": "HTML",
    "country": "Italy",
    "category": "Undergraduate Admissions",
    "features": "Procedures biennale 2026-2028; visa deadline 30/11; pre-enrollment only here; migration risk assessment",
    "language": "English/Italian",
    "appFee": "Free",
    "deadlinePattern": "Visa: Nov 30 (2026/27), Oct 31 (2027/28)",
    "notes": "Non-EU students abroad mandatory"
  },
  {
    "name": "University of Bologna Guide",
    "baseUrl": "https://www.unibo.it/en/attachments/guide-universitaly/@@download/file/Guide-FAQ-Universitaly-for-students-2025-26-ENG.pdf",
    "kind": "UNIVERSITY",
    "tier": "B",
    "fetchStrategy": "HTML",
    "country": "Italy",
    "category": "Undergraduate Admissions",
    "features": "Step-by-step pre-enrollment; conditional/unconditional validation; TOLC test; tuition payment; document upload dual (Universitaly + GOMP)",
    "language": "English",
    "appFee": "Free",
    "deadlinePattern": "Per university",
    "notes": "Oldest university in Western world"
  },
  {
    "name": "Sapienza Universitaly Guide",
    "baseUrl": "https://www.uniroma1.it/sites/default/files/field_file_allegati/universitaly_guide.docx_0.pdf",
    "kind": "UNIVERSITY",
    "tier": "B",
    "fetchStrategy": "HTML",
    "country": "Italy",
    "category": "Undergraduate Admissions",
    "features": "Detailed screenshots: register; pre-enroll; upload qualification; embassy selection; validation email",
    "language": "English/Italian",
    "appFee": "Free",
    "deadlinePattern": "Per university",
    "notes": "Largest European university"
  },
  {
    "name": "CampusChina (CSC)",
    "baseUrl": "https://www.campuschina.org",
    "kind": "NGO",
    "tier": "B",
    "fetchStrategy": "HTML",
    "country": "China",
    "category": "Scholarships & Admissions",
    "features": "Official CSC portal: Chinese Government Scholarship (Type A embassy / Type B university); 252 designated universities; CSCA test mandatory for bachelor's",
    "language": "English/Chinese",
    "appFee": "Free",
    "deadlinePattern": "Type A: ~Feb; Type B: ~Apr",
    "notes": "China Scholarship Council"
  },
  {
    "name": "China Scholarship Council",
    "baseUrl": "https://www.csc.edu.cn",
    "kind": "GOVERNMENT",
    "tier": "A",
    "fetchStrategy": "HTML",
    "country": "China",
    "category": "Scholarships",
    "features": "Scholarship programs; directory 252 universities; studyinchina.csc.edu.cn application system",
    "language": "English/Chinese",
    "appFee": "Free",
    "deadlinePattern": "Continuous",
    "notes": "National scholarship admin body"
  },
  {
    "name": "Nankai University CSC",
    "baseUrl": "https://ensie.nankai.edu.cn",
    "kind": "NGO",
    "tier": "B",
    "fetchStrategy": "HTML",
    "country": "China",
    "category": "Scholarships",
    "features": "Silk Road Program (Vietnam included); HSK5/IELTS6; CSCA test; monthly stipend 2500/3000 RMB; interview; dual application",
    "language": "English/Chinese",
    "appFee": "Free",
    "deadlinePattern": "~May",
    "notes": "Belt & Road focused"
  },
  {
    "name": "Central South University CSC",
    "baseUrl": "https://intl.csu.edu.cn/Admission/Scholarship/type_b.htm",
    "kind": "NGO",
    "tier": "B",
    "fetchStrategy": "HTML",
    "country": "China",
    "category": "Scholarships",
    "features": "Type B University Program; Silk Road; agency code 10533; application fee CNY 500; annual review May",
    "language": "English/Chinese",
    "appFee": "CNY 500",
    "deadlinePattern": "~Apr",
    "notes": "Mining/metallurgy strength"
  },
  {
    "name": "swissuniversities",
    "baseUrl": "https://www.swissuniversities.ch",
    "kind": "UNIVERSITY",
    "tier": "B",
    "fetchStrategy": "HTML",
    "country": "Switzerland",
    "category": "Undergraduate Admissions",
    "features": "Umbrella organization: admission requirements by country; IB/International A-levels/GCE recognition; ECUS exam; studyprogrammes.ch database",
    "language": "English/German/French/Italian",
    "appFee": "Free",
    "deadlinePattern": "Continuous",
    "notes": "Swiss higher education coordination body"
  },
  {
    "name": "UNIL Admission",
    "baseUrl": "https://www.unil.ch/unil/en/home/menuinst/etudier/immatriculations-et-inscriptions/bachelor-avec-diplome-etranger.html",
    "kind": "UNIVERSITY",
    "tier": "B",
    "fetchStrategy": "HTML",
    "country": "Switzerland",
    "category": "Undergraduate Admissions",
    "features": "Country-specific requirements; Lisbon Convention; medicine deadline 15/2 swissuniversities registration",
    "language": "English/French",
    "appFee": "Free",
    "deadlinePattern": "Apr 30 (general); Feb 15 (medicine)",
    "notes": "University of Lausanne"
  },
  {
    "name": "UNIGE Registration",
    "baseUrl": "https://www.unige.ch/immatriculations/en/procedure",
    "kind": "UNIVERSITY",
    "tier": "B",
    "fetchStrategy": "HTML",
    "country": "Switzerland",
    "category": "Undergraduate Admissions",
    "features": "Online enrollment; foreign diploma fee CHF 65; postal submission; enrollment certificate; appointment system",
    "language": "English/French",
    "appFee": "CHF 65 (foreign diploma)",
    "deadlinePattern": "Apr 30",
    "notes": "University of Geneva"
  },
  {
    "name": "University of Bern Application",
    "baseUrl": "https://www.unibe.ch/unibe/portal/content/e1006/e1029/e1031/e1036/e8825/e46400/e46401/Bachelor_eng.pdf",
    "kind": "UNIVERSITY",
    "tier": "B",
    "fetchStrategy": "HTML",
    "country": "Switzerland",
    "category": "Undergraduate Admissions",
    "features": "Application fee CHF 105/155; hard copies by post; country-specific admission proof; German C1; checklist",
    "language": "English/German",
    "appFee": "CHF 105/155",
    "deadlinePattern": "Apr 30",
    "notes": "Capital university"
  },
  {
    "name": "Study in Finland",
    "baseUrl": "https://www.studyinfinland.fi",
    "kind": "UNIVERSITY",
    "tier": "B",
    "fetchStrategy": "HTML",
    "country": "Finland",
    "category": "Undergraduate Admissions",
    "features": "Official Finnish higher education portal; program search; scholarship info; application via Studyinfo.fi",
    "language": "English/Finnish",
    "appFee": "Free",
    "deadlinePattern": "Jan (joint application)",
    "notes": "Finnish National Agency for Education"
  },
  {
    "name": "University Admissions Sweden",
    "baseUrl": "https://www.universityadmissions.se",
    "kind": "UNIVERSITY",
    "tier": "B",
    "fetchStrategy": "HTML",
    "country": "Sweden",
    "category": "Undergraduate Admissions",
    "features": "Centralized applications for Swedish universities; document upload; ranking; tuition fees for non-EU",
    "language": "English/Swedish",
    "appFee": "Free",
    "deadlinePattern": "Mid Jan (autumn); Mid Aug (spring)",
    "notes": "Swedish Council for Higher Education"
  },
  {
    "name": "Study in Flanders",
    "baseUrl": "https://www.studyinflanders.be",
    "kind": "UNIVERSITY",
    "tier": "B",
    "fetchStrategy": "HTML",
    "country": "Belgium",
    "category": "Undergraduate Admissions",
    "features": "Flemish higher education portal; program search; scholarship info; visa guidance",
    "language": "English/Dutch",
    "appFee": "Free",
    "deadlinePattern": "Continuous",
    "notes": "Flanders region"
  },
  {
    "name": "Wallonie-Bruxelles Campus",
    "baseUrl": "https://www.wallonie-bruxelles-campus.be",
    "kind": "UNIVERSITY",
    "tier": "B",
    "fetchStrategy": "HTML",
    "country": "Belgium",
    "category": "Undergraduate Admissions",
    "features": "French-speaking Belgium higher education; program search; admission procedures",
    "language": "French",
    "appFee": "Free",
    "deadlinePattern": "Continuous",
    "notes": "Wallonia-Brussels Federation"
  },
  {
    "name": "Study in Russia",
    "baseUrl": "https://studyinrussia.ru",
    "kind": "UNIVERSITY",
    "tier": "B",
    "fetchStrategy": "HTML",
    "country": "Russia",
    "category": "Undergraduate Admissions",
    "features": "Russian government scholarship (quotas); program search; university rankings; preparatory courses",
    "language": "English/Russian",
    "appFee": "Free",
    "deadlinePattern": "Feb - Jun (quota applications)",
    "notes": "Rossotrudnichestvo managed"
  },
  {
    "name": "Study in Taiwan",
    "baseUrl": "https://www.studyintaiwan.org",
    "kind": "UNIVERSITY",
    "tier": "B",
    "fetchStrategy": "HTML",
    "country": "Taiwan",
    "category": "Undergraduate Admissions",
    "features": "MOE Taiwan portal; scholarship (Taiwan Scholarship, Huayu Enrichment); program search; application procedures",
    "language": "English/Chinese",
    "appFee": "Free",
    "deadlinePattern": "Mar - May (varies)",
    "notes": "Ministry of Education Taiwan"
  },
  {
    "name": "Study in Hong Kong",
    "baseUrl": "https://www.studyinhongkong.edu.hk",
    "kind": "UNIVERSITY",
    "tier": "B",
    "fetchStrategy": "HTML",
    "country": "Hong Kong",
    "category": "Undergraduate Admissions",
    "features": "UGC portal; 8 funded universities; non-local admission schemes; scholarship info",
    "language": "English/Chinese",
    "appFee": "Free",
    "deadlinePattern": "Dec - Jun (varies)",
    "notes": "University Grants Committee"
  },
  {
    "name": "Study in NZ",
    "baseUrl": "https://www.studyinnewzealand.govt.nz",
    "kind": "GOVERNMENT",
    "tier": "A",
    "fetchStrategy": "HTML",
    "country": "New Zealand",
    "category": "Undergraduate Admissions",
    "features": "Official NZ promotion; program search; visa guide; scholarship info; cost calculator",
    "language": "English",
    "appFee": "Free",
    "deadlinePattern": "Continuous",
    "notes": "Education New Zealand"
  },
  {
    "name": "NZQA",
    "baseUrl": "https://www.nzqa.govt.nz",
    "kind": "GOVERNMENT",
    "tier": "A",
    "fetchStrategy": "HTML",
    "country": "New Zealand",
    "category": "Qualifications",
    "features": "Qualifications recognition; NCEA; international qualification assessment; provider registration",
    "language": "English",
    "appFee": "Free",
    "deadlinePattern": "Continuous",
    "notes": "New Zealand Qualifications Authority"
  },
  {
    "name": "ĐH Bách khoa TP.HCM",
    "baseUrl": "https://hcmut.edu.vn",
    "kind": "UNIVERSITY",
    "tier": "A",
    "fetchStrategy": "HTML",
    "country": "Vietnam",
    "category": "Undergraduate Admissions",
    "appFee": "Free",
    "features": "Cổng thông tin tuyển sinh & học bổng chính thức",
    "language": "Vietnamese",
    "deadlinePattern": "Theo kỳ tuyển sinh hàng năm",
    "notes": "Nguồn được xác thực bởi hệ thống"
  },
  {
    "name": "ĐHQG TP.HCM (VNU-HCM)",
    "baseUrl": "https://vnuhcm.edu.vn",
    "kind": "UNIVERSITY",
    "tier": "A",
    "fetchStrategy": "HTML",
    "country": "Vietnam",
    "category": "Undergraduate Admissions",
    "appFee": "Free",
    "features": "Cổng thông tin tuyển sinh & học bổng chính thức",
    "language": "Vietnamese",
    "deadlinePattern": "Theo kỳ tuyển sinh hàng năm",
    "notes": "Nguồn được xác thực bởi hệ thống"
  },
  {
    "name": "ĐH Y Dược TP.HCM (UMP)",
    "baseUrl": "https://ump.edu.vn",
    "kind": "UNIVERSITY",
    "tier": "A",
    "fetchStrategy": "HTML",
    "country": "Vietnam",
    "category": "Undergraduate Admissions",
    "appFee": "Free",
    "features": "Cổng thông tin tuyển sinh & học bổng chính thức",
    "language": "Vietnamese",
    "deadlinePattern": "Theo kỳ tuyển sinh hàng năm",
    "notes": "Nguồn được xác thực bởi hệ thống"
  },
  {
    "name": "ĐH Sư phạm HN (HNUE)",
    "baseUrl": "https://hnue.edu.vn",
    "kind": "UNIVERSITY",
    "tier": "A",
    "fetchStrategy": "HTML",
    "country": "Vietnam",
    "category": "Undergraduate Admissions",
    "appFee": "Free",
    "features": "Cổng thông tin tuyển sinh & học bổng chính thức",
    "language": "Vietnamese",
    "deadlinePattern": "Theo kỳ tuyển sinh hàng năm",
    "notes": "Nguồn được xác thực bởi hệ thống"
  },
  {
    "name": "VinUni",
    "baseUrl": "https://vinuni.edu.vn",
    "kind": "UNIVERSITY",
    "tier": "A",
    "fetchStrategy": "HTML",
    "country": "Vietnam",
    "category": "Scholarships & Admissions",
    "appFee": "Free",
    "features": "Cổng thông tin tuyển sinh & học bổng chính thức",
    "language": "Vietnamese",
    "deadlinePattern": "Theo kỳ tuyển sinh hàng năm",
    "notes": "Nguồn được xác thực bởi hệ thống"
  },
  {
    "name": "IDP Vietnam - Học Bổng Du Học",
    "baseUrl": "https://www.idp.com",
    "kind": "PORTAL",
    "tier": "A",
    "fetchStrategy": "HTML",
    "country": "Vietnam",
    "category": "Scholarships",
    "appFee": "Free",
    "features": "Cổng thông tin tuyển sinh & học bổng chính thức",
    "language": "Vietnamese",
    "deadlinePattern": "Theo kỳ tuyển sinh hàng năm",
    "notes": "Nguồn được xác thực bởi hệ thống"
  },
  {
    "name": "ĐH Đà Nẵng (UD)",
    "baseUrl": "https://udn.vn",
    "kind": "UNIVERSITY",
    "tier": "B",
    "fetchStrategy": "HTML",
    "country": "Vietnam",
    "category": "Undergraduate Admissions",
    "appFee": "Free",
    "features": "Cổng thông tin tuyển sinh & học bổng chính thức",
    "language": "Vietnamese",
    "deadlinePattern": "Theo kỳ tuyển sinh hàng năm",
    "notes": "Nguồn được xác thực bởi hệ thống"
  },
  {
    "name": "ĐH Cần Thơ (CTU)",
    "baseUrl": "https://ctu.edu.vn",
    "kind": "UNIVERSITY",
    "tier": "B",
    "fetchStrategy": "HTML",
    "country": "Vietnam",
    "category": "Undergraduate Admissions",
    "appFee": "Free",
    "features": "Cổng thông tin tuyển sinh & học bổng chính thức",
    "language": "Vietnamese",
    "deadlinePattern": "Theo kỳ tuyển sinh hàng năm",
    "notes": "Nguồn được xác thực bởi hệ thống"
  },
  {
    "name": "ĐH Thái Nguyên (TNU)",
    "baseUrl": "https://tnu.edu.vn",
    "kind": "UNIVERSITY",
    "tier": "B",
    "fetchStrategy": "HTML",
    "country": "Vietnam",
    "category": "Undergraduate Admissions",
    "appFee": "Free",
    "features": "Cổng thông tin tuyển sinh & học bổng chính thức",
    "language": "Vietnamese",
    "deadlinePattern": "Theo kỳ tuyển sinh hàng năm",
    "notes": "Nguồn được xác thực bởi hệ thống"
  },
  {
    "name": "ĐH Vinh",
    "baseUrl": "https://vinhuni.edu.vn",
    "kind": "UNIVERSITY",
    "tier": "B",
    "fetchStrategy": "HTML",
    "country": "Vietnam",
    "category": "Undergraduate Admissions",
    "appFee": "Free",
    "features": "Cổng thông tin tuyển sinh & học bổng chính thức",
    "language": "Vietnamese",
    "deadlinePattern": "Theo kỳ tuyển sinh hàng năm",
    "notes": "Nguồn được xác thực bởi hệ thống"
  },
  {
    "name": "ĐH Quy Nhơn (QNU)",
    "baseUrl": "https://qnu.edu.vn",
    "kind": "UNIVERSITY",
    "tier": "B",
    "fetchStrategy": "HTML",
    "country": "Vietnam",
    "category": "Undergraduate Admissions",
    "appFee": "Free",
    "features": "Cổng thông tin tuyển sinh & học bổng chính thức",
    "language": "Vietnamese",
    "deadlinePattern": "Theo kỳ tuyển sinh hàng năm",
    "notes": "Nguồn được xác thực bởi hệ thống"
  },
  {
    "name": "ĐH Tây Nguyên",
    "baseUrl": "https://ttn.edu.vn",
    "kind": "UNIVERSITY",
    "tier": "B",
    "fetchStrategy": "HTML",
    "country": "Vietnam",
    "category": "Undergraduate Admissions",
    "appFee": "Free",
    "features": "Cổng thông tin tuyển sinh & học bổng chính thức",
    "language": "Vietnamese",
    "deadlinePattern": "Theo kỳ tuyển sinh hàng năm",
    "notes": "Nguồn được xác thực bởi hệ thống"
  },
  {
    "name": "Học viện Ngoại giao (DAV)",
    "baseUrl": "https://dav.edu.vn",
    "kind": "UNIVERSITY",
    "tier": "B",
    "fetchStrategy": "HTML",
    "country": "Vietnam",
    "category": "Undergraduate Admissions",
    "appFee": "Free",
    "features": "Cổng thông tin tuyển sinh & học bổng chính thức",
    "language": "Vietnamese",
    "deadlinePattern": "Theo kỳ tuyển sinh hàng năm",
    "notes": "Nguồn được xác thực bởi hệ thống"
  },
  {
    "name": "Học viện Ngân hàng (BA)",
    "baseUrl": "https://hvnh.edu.vn",
    "kind": "UNIVERSITY",
    "tier": "B",
    "fetchStrategy": "HTML",
    "country": "Vietnam",
    "category": "Undergraduate Admissions",
    "appFee": "Free",
    "features": "Cổng thông tin tuyển sinh & học bổng chính thức",
    "language": "Vietnamese",
    "deadlinePattern": "Theo kỳ tuyển sinh hàng năm",
    "notes": "Nguồn được xác thực bởi hệ thống"
  },
  {
    "name": "ĐH Giao thông Vận tải (UTC)",
    "baseUrl": "https://utc.edu.vn",
    "kind": "UNIVERSITY",
    "tier": "B",
    "fetchStrategy": "HTML",
    "country": "Vietnam",
    "category": "Undergraduate Admissions",
    "appFee": "Free",
    "features": "Cổng thông tin tuyển sinh & học bổng chính thức",
    "language": "Vietnamese",
    "deadlinePattern": "Theo kỳ tuyển sinh hàng năm",
    "notes": "Nguồn được xác thực bởi hệ thống"
  },
  {
    "name": "ĐH Xây dựng (HUCE)",
    "baseUrl": "https://huce.edu.vn",
    "kind": "UNIVERSITY",
    "tier": "B",
    "fetchStrategy": "HTML",
    "country": "Vietnam",
    "category": "Undergraduate Admissions",
    "appFee": "Free",
    "features": "Cổng thông tin tuyển sinh & học bổng chính thức",
    "language": "Vietnamese",
    "deadlinePattern": "Theo kỳ tuyển sinh hàng năm",
    "notes": "Nguồn được xác thực bởi hệ thống"
  },
  {
    "name": "ĐH Thương mại (TMU)",
    "baseUrl": "https://tmu.edu.vn",
    "kind": "UNIVERSITY",
    "tier": "B",
    "fetchStrategy": "HTML",
    "country": "Vietnam",
    "category": "Undergraduate Admissions",
    "appFee": "Free",
    "features": "Cổng thông tin tuyển sinh & học bổng chính thức",
    "language": "Vietnamese",
    "deadlinePattern": "Theo kỳ tuyển sinh hàng năm",
    "notes": "Nguồn được xác thực bởi hệ thống"
  },
  {
    "name": "ĐH Kinh tế TP.HCM (UEH)",
    "baseUrl": "https://ueh.edu.vn",
    "kind": "UNIVERSITY",
    "tier": "B",
    "fetchStrategy": "HTML",
    "country": "Vietnam",
    "category": "Undergraduate Admissions",
    "appFee": "Free",
    "features": "Cổng thông tin tuyển sinh & học bổng chính thức",
    "language": "Vietnamese",
    "deadlinePattern": "Theo kỳ tuyển sinh hàng năm",
    "notes": "Nguồn được xác thực bởi hệ thống"
  },
  {
    "name": "ĐH Công nghệ Thông tin ĐHQG-HCM (UIT)",
    "baseUrl": "https://uit.edu.vn",
    "kind": "UNIVERSITY",
    "tier": "B",
    "fetchStrategy": "HTML",
    "country": "Vietnam",
    "category": "Undergraduate Admissions",
    "appFee": "Free",
    "features": "Cổng thông tin tuyển sinh & học bổng chính thức",
    "language": "Vietnamese",
    "deadlinePattern": "Theo kỳ tuyển sinh hàng năm",
    "notes": "Nguồn được xác thực bởi hệ thống"
  },
  {
    "name": "ĐH Quốc tế ĐHQG-HCM (IU)",
    "baseUrl": "https://hcmiu.edu.vn",
    "kind": "UNIVERSITY",
    "tier": "B",
    "fetchStrategy": "HTML",
    "country": "Vietnam",
    "category": "Undergraduate Admissions",
    "appFee": "Free",
    "features": "Cổng thông tin tuyển sinh & học bổng chính thức",
    "language": "Vietnamese",
    "deadlinePattern": "Theo kỳ tuyển sinh hàng năm",
    "notes": "Nguồn được xác thực bởi hệ thống"
  },
  {
    "name": "ĐH Tôn Đức Thắng (TDTU)",
    "baseUrl": "https://tdtu.edu.vn",
    "kind": "UNIVERSITY",
    "tier": "B",
    "fetchStrategy": "HTML",
    "country": "Vietnam",
    "category": "Undergraduate Admissions",
    "appFee": "Free",
    "features": "Cổng thông tin tuyển sinh & học bổng chính thức",
    "language": "Vietnamese",
    "deadlinePattern": "Theo kỳ tuyển sinh hàng năm",
    "notes": "Nguồn được xác thực bởi hệ thống"
  },
  {
    "name": "ĐH Khoa học Tự nhiên ĐHQGHN (HUS)",
    "baseUrl": "https://hus.vnu.edu.vn",
    "kind": "UNIVERSITY",
    "tier": "B",
    "fetchStrategy": "HTML",
    "country": "Vietnam",
    "category": "Undergraduate Admissions",
    "appFee": "Free",
    "features": "Cổng thông tin tuyển sinh & học bổng chính thức",
    "language": "Vietnamese",
    "deadlinePattern": "Theo kỳ tuyển sinh hàng năm",
    "notes": "Nguồn được xác thực bởi hệ thống"
  },
  {
    "name": "ĐH Công nghệ ĐHQGHN (UET)",
    "baseUrl": "https://uet.vnu.edu.vn",
    "kind": "UNIVERSITY",
    "tier": "B",
    "fetchStrategy": "HTML",
    "country": "Vietnam",
    "category": "Undergraduate Admissions",
    "appFee": "Free",
    "features": "Cổng thông tin tuyển sinh & học bổng chính thức",
    "language": "Vietnamese",
    "deadlinePattern": "Theo kỳ tuyển sinh hàng năm",
    "notes": "Nguồn được xác thực bởi hệ thống"
  },
  {
    "name": "ĐH Phenikaa",
    "baseUrl": "https://phenikaa-uni.edu.vn",
    "kind": "UNIVERSITY",
    "tier": "B",
    "fetchStrategy": "HTML",
    "country": "Vietnam",
    "category": "Undergraduate Admissions",
    "appFee": "Free",
    "features": "Cổng thông tin tuyển sinh & học bổng chính thức",
    "language": "Vietnamese",
    "deadlinePattern": "Theo kỳ tuyển sinh hàng năm",
    "notes": "Nguồn được xác thực bởi hệ thống"
  },
  {
    "name": "HUTECH",
    "baseUrl": "https://hutech.edu.vn",
    "kind": "UNIVERSITY",
    "tier": "B",
    "fetchStrategy": "HTML",
    "country": "Vietnam",
    "category": "Undergraduate Admissions",
    "appFee": "Free",
    "features": "Cổng thông tin tuyển sinh & học bổng chính thức",
    "language": "Vietnamese",
    "deadlinePattern": "Theo kỳ tuyển sinh hàng năm",
    "notes": "Nguồn được xác thực bởi hệ thống"
  },
  {
    "name": "UEF",
    "baseUrl": "https://uef.edu.vn",
    "kind": "UNIVERSITY",
    "tier": "B",
    "fetchStrategy": "HTML",
    "country": "Vietnam",
    "category": "Undergraduate Admissions",
    "appFee": "Free",
    "features": "Cổng thông tin tuyển sinh & học bổng chính thức",
    "language": "Vietnamese",
    "deadlinePattern": "Theo kỳ tuyển sinh hàng năm",
    "notes": "Nguồn được xác thực bởi hệ thống"
  },
  {
    "name": "ĐH Hoa Sen (HSU)",
    "baseUrl": "https://hoasen.edu.vn",
    "kind": "UNIVERSITY",
    "tier": "B",
    "fetchStrategy": "HTML",
    "country": "Vietnam",
    "category": "Undergraduate Admissions",
    "appFee": "Free",
    "features": "Cổng thông tin tuyển sinh & học bổng chính thức",
    "language": "Vietnamese",
    "deadlinePattern": "Theo kỳ tuyển sinh hàng năm",
    "notes": "Nguồn được xác thực bởi hệ thống"
  },
  {
    "name": "KOICA Vietnam",
    "baseUrl": "https://www.koica.go.kr",
    "kind": "GOVERNMENT",
    "tier": "B",
    "fetchStrategy": "HTML",
    "country": "South Korea",
    "category": "Scholarships",
    "appFee": "Free",
    "features": "Cổng thông tin tuyển sinh & học bổng chính thức",
    "language": "Vietnamese",
    "deadlinePattern": "Theo kỳ tuyển sinh hàng năm",
    "notes": "Nguồn được xác thực bởi hệ thống"
  },
  {
    "name": "JICA Vietnam",
    "baseUrl": "https://www.jica.go.jp",
    "kind": "GOVERNMENT",
    "tier": "B",
    "fetchStrategy": "HTML",
    "country": "Japan",
    "category": "Scholarships",
    "appFee": "Free",
    "features": "Cổng thông tin tuyển sinh & học bổng chính thức",
    "language": "Vietnamese",
    "deadlinePattern": "Theo kỳ tuyển sinh hàng năm",
    "notes": "Nguồn được xác thực bởi hệ thống"
  },
  {
    "name": "ADB Scholarships",
    "baseUrl": "https://www.adb.org",
    "kind": "NGO",
    "tier": "B",
    "fetchStrategy": "HTML",
    "country": "International",
    "category": "Scholarships",
    "appFee": "Free",
    "features": "Cổng thông tin tuyển sinh & học bổng chính thức",
    "language": "Vietnamese",
    "deadlinePattern": "Theo kỳ tuyển sinh hàng năm",
    "notes": "Nguồn được xác thực bởi hệ thống"
  },
  {
    "name": "Quỹ Đổi mới Sáng tạo Vingroup (VinIF)",
    "baseUrl": "https://vinif.org",
    "kind": "CORPORATE",
    "tier": "C",
    "fetchStrategy": "HTML",
    "country": "Vietnam",
    "category": "Scholarships",
    "appFee": "Free",
    "features": "Cổng thông tin tuyển sinh & học bổng chính thức",
    "language": "Vietnamese",
    "deadlinePattern": "Theo kỳ tuyển sinh hàng năm",
    "notes": "Nguồn được xác thực bởi hệ thống"
  },
  {
    "name": "Quỹ Học bổng Thắp Sáng Niềm Tin",
    "baseUrl": "https://thapsangniemtin.vn",
    "kind": "NGO",
    "tier": "C",
    "fetchStrategy": "HTML",
    "country": "Vietnam",
    "category": "Scholarships",
    "appFee": "Free",
    "features": "Cổng thông tin tuyển sinh & học bổng chính thức",
    "language": "Vietnamese",
    "deadlinePattern": "Theo kỳ tuyển sinh hàng năm",
    "notes": "Nguồn được xác thực bởi hệ thống"
  },
  {
    "name": "Quỹ Lawrence S. Ting",
    "baseUrl": "https://lawrencestingfoundation.org",
    "kind": "NGO",
    "tier": "C",
    "fetchStrategy": "HTML",
    "country": "Vietnam",
    "category": "Scholarships",
    "appFee": "Free",
    "features": "Cổng thông tin tuyển sinh & học bổng chính thức",
    "language": "Vietnamese",
    "deadlinePattern": "Theo kỳ tuyển sinh hàng năm",
    "notes": "Nguồn được xác thực bởi hệ thống"
  },
  {
    "name": "Tập đoàn FPT",
    "baseUrl": "https://fpt.com.vn",
    "kind": "CORPORATE",
    "tier": "C",
    "fetchStrategy": "HTML",
    "country": "Vietnam",
    "category": "Internship & Jobs",
    "appFee": "Free",
    "features": "Cổng thông tin tuyển sinh & học bổng chính thức",
    "language": "Vietnamese",
    "deadlinePattern": "Theo kỳ tuyển sinh hàng năm",
    "notes": "Nguồn được xác thực bởi hệ thống"
  },
  {
    "name": "Viettel",
    "baseUrl": "https://viettel.com.vn",
    "kind": "CORPORATE",
    "tier": "C",
    "fetchStrategy": "HTML",
    "country": "Vietnam",
    "category": "Internship & Jobs",
    "appFee": "Free",
    "features": "Cổng thông tin tuyển sinh & học bổng chính thức",
    "language": "Vietnamese",
    "deadlinePattern": "Theo kỳ tuyển sinh hàng năm",
    "notes": "Nguồn được xác thực bởi hệ thống"
  },
  {
    "name": "Samsung Vietnam",
    "baseUrl": "https://samsung.com/vn",
    "kind": "CORPORATE",
    "tier": "C",
    "fetchStrategy": "HTML",
    "country": "Vietnam",
    "category": "Internship & Jobs",
    "appFee": "Free",
    "features": "Cổng thông tin tuyển sinh & học bổng chính thức",
    "language": "Vietnamese",
    "deadlinePattern": "Theo kỳ tuyển sinh hàng năm",
    "notes": "Nguồn được xác thực bởi hệ thống"
  },
  {
    "name": "Honda Vietnam",
    "baseUrl": "https://honda.com.vn",
    "kind": "CORPORATE",
    "tier": "C",
    "fetchStrategy": "HTML",
    "country": "Vietnam",
    "category": "Internship & Jobs",
    "appFee": "Free",
    "features": "Cổng thông tin tuyển sinh & học bổng chính thức",
    "language": "Vietnamese",
    "deadlinePattern": "Theo kỳ tuyển sinh hàng năm",
    "notes": "Nguồn được xác thực bởi hệ thống"
  },
  {
    "name": "Toyota Vietnam Foundation",
    "baseUrl": "https://toyotavn.com.vn",
    "kind": "CORPORATE",
    "tier": "C",
    "fetchStrategy": "HTML",
    "country": "Vietnam",
    "category": "Scholarships",
    "appFee": "Free",
    "features": "Cổng thông tin tuyển sinh & học bổng chính thức",
    "language": "Vietnamese",
    "deadlinePattern": "Theo kỳ tuyển sinh hàng năm",
    "notes": "Nguồn được xác thực bởi hệ thống"
  },
  {
    "name": "Scholarship.vn",
    "baseUrl": "https://scholarship.vn",
    "kind": "PORTAL",
    "tier": "C",
    "fetchStrategy": "HTML",
    "country": "Vietnam",
    "category": "Scholarships",
    "appFee": "Free",
    "features": "Cổng thông tin tuyển sinh & học bổng chính thức",
    "language": "Vietnamese",
    "deadlinePattern": "Theo kỳ tuyển sinh hàng năm",
    "notes": "Nguồn được xác thực bởi hệ thống"
  },
  {
    "name": "Kênh Tuyển Sinh",
    "baseUrl": "https://kenhtuyensinh.vn",
    "kind": "PORTAL",
    "tier": "C",
    "fetchStrategy": "HTML",
    "country": "Vietnam",
    "category": "Undergraduate Admissions",
    "appFee": "Free",
    "features": "Cổng thông tin tuyển sinh & học bổng chính thức",
    "language": "Vietnamese",
    "deadlinePattern": "Theo kỳ tuyển sinh hàng năm",
    "notes": "Nguồn được xác thực bởi hệ thống"
  },
  {
    "name": "Cổng Thông Tin Học Bổng Quốc Tế (RSS Feed)",
    "baseUrl": "https://scholarshipdb.net/scholarships.xml",
    "kind": "PORTAL",
    "tier": "C",
    "fetchStrategy": "RSS",
    "country": "International",
    "category": "Scholarships",
    "appFee": "Free",
    "features": "Cổng thông tin tuyển sinh & học bổng chính thức",
    "language": "Vietnamese",
    "deadlinePattern": "Theo kỳ tuyển sinh hàng năm",
    "notes": "Nguồn được xác thực bởi hệ thống"
  }
];
